services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - ganache
    ports:
      - "5000:5000"
    environment:
      - GANACHE_URL=http://ganache:8545
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0